"""Add CMS category

Revision ID: 41f61fcbf1cb
Revises: fe4c02df43ca
Create Date: 2025-11-29 22:24:25.630171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f61fcbf1cb'
down_revision = 'fe4c02df43ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
