-- Run once in the Supabase SQL editor before deploying the attendance audit.
-- This table contains only authenticated Think.4U meeting joins; it does not
-- expose a Jitsi room or a recording URL.

create table if not exists public.meeting_attendance (
  id bigint generated by default as identity primary key,
  meeting_key text not null,
  appointment_id bigint,
  user_id text not null,
  email text not null,
  name text not null,
  role text not null check (role in ('admin', 'coordinator', 'participant')),
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (meeting_key, user_id)
);

create index if not exists meeting_attendance_meeting_key_idx
  on public.meeting_attendance (meeting_key);

alter table public.meeting_attendance enable row level security;

-- The web application uses its server-side Supabase credentials. Do not add
-- anonymous SELECT/INSERT policies; that would expose participant audit data.
